import React from "react";
import "../../assets/css/about/about.css";

const Shariah = () => {
  return (
    <main>
      <section class="mt-100 font-poppins weight-700 m-mt-5">
        <div className="container">
          <div className="row">
            <div className="col-12 text-center mb-3">
              <h3 className="about-us-head text-green weight-700">
                Shariah Screening Methodology
              </h3>
            </div>
            <div className="col-12 text-left mt-4">
              <h3 className="font-poppins weight-700 font-20 heading-about my-2">
                ***Limitations and Disclaimer
              </h3>
              <text className="font-15 weight-400">
                Our current limitation is that we assume all debt in non-Islamic
                countries involves interest. This means that if a company has
                debt that is free of interest, it won't be reflected in our
                screening process. We acknowledge that errors can occur and are
                continually improving. Note that we do not provide individual
                investment advice and strongly suggest that you consult a
                Shariah expert before making any investments. We appreciate your
                feedback, inquiries, and constructive criticism. Thank you, may
                Allah reward you well.
              </text>
            </div>
            <div className="col-12 ">
              <h3 className="font-poppins weight-700 font-20 heading-about my-2 text-center">
                Summary
              </h3>
              <text className="font-15 weight-400">
                <ul className="ul-left p-0">
                  MyRizq is a bootstrapped tech start up that aims to provide
                  Shairah screening for stocks. Let us be clear that our
                screening methodology is not perfect however our screening of
                  stocks follows Shariah standards as established by leading
                  institutions and indices. As of now we only use the Accounting
                  and Auditing Organization for Islamic Financial Institutions
                  (AAOIFI) guidelines to screen stocks. In the coming
                  weeks-months we plan to introduce other standards for users
                  such as the following:
                  <li>Standard and Poor’s Shariah Indices (S&P)</li>
                  <li>Dow Jones Islamic Market Indexes (DJIMI)</li>
                  <li>
                    Financial Times Stock Exchange Shariah Global Equity Index
                    Series (FTSE)
                  </li>
                  <li>Standard and Poor’s Shariah Indices (S&P)</li>
                  <li>
                    Morgan Stanley Capital International World Islamic Indices
                    (MSCI)
                  </li>
                  <li>Thompson Reuters Ideal Ratings Islamic Indices</li>
                  <li>ISRA Bloomberg Shariah Stock Screening Indices</li>
                </ul>
              </text>
            </div>

            <div className="col-12 ">
              <h3 className="font-poppins weight-700 font-20 heading-about my-2 text-center">
                Qualitative Screening
              </h3>
              <text className="font-15 weight-400">
                <ul className="ul-left p-0">
                  The first criterion of all the Shariah screening methodologies
                  is to exclude companies whose main business activity is
                  impermissible by the Shariah teachings such as the following:
                  <li>
                    Entertainment (hotels, gambling, cinema/movie theatres,
                    music, pornography, etc)
                  </li>
                  <li>Weapons and defence</li>
                  <li>
                    Conventional financial services (ie banking, insurance and
                    so on)
                  </li>
                  <li>
                    Biotechnology companies involved in human/animal genetic
                  </li>
                  <li>
                    Morgan Stanley Capital International World Islamic Indices
                    (MSCI)
                  </li>
                  <li>Thompson Reuters Ideal Ratings Islamic Indices</li>
                  <li>ISRA Bloomberg Shariah Stock Screening Indices</li>
                  The test a company must satisfy is that at least 95% of its
                  gross revenues are generated by activities other than those
                  mentioned above.
                </ul>
              </text>
            </div>
            <div className="col-12 ">
              <h3 className="font-poppins weight-700 font-20 heading-about my-2 text-center">
                Quantitative Screening
              </h3>
              <text className="font-15 weight-400">
                <ul className="ul-left p-0">
                  As of now MyRizq only uses the AAOIFI guidelines to do the
                  Quantitive screening of stocks. AAOIFI screens stocks based on
                  the following guidelines:
                  <li>
                    Interest taking deposits less than 30% to market
                    capitalization of total
                  </li>
                  <li>
                    Interest bearing debt less than 30% to market capitalization
                    of the corporation
                  </li>
                  <li>
                    Total market value of illiquid assets more than 30% to
                    market value of the total assets.
                  </li>
                </ul>
              </text>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
};

export default Shariah;
